# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1c0340a5580339604a0c4d02509427d20c158046e6ce381aaa9a119a65af5bc638ff67a249b01ab851bfaf954a5853fa880e899e0c6c6450e761f99c370d054

test:
  secret_key_base: bec8c69567c364b3f747653c57f0f292b0431e23a151587ccde4392c135d7cffa690499e8f291f057d748637aaef9bf5d8852fcbdfecf0b47b65313058a93134

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
